# Use the updated base image
FROM erc-mars-rover_base:latest

ARG ROS_DISTRO=humble
ARG BASE_FOLDER=/root/orin
ARG ROS_WORKSPACE_NAME=ERC-Mars-Rover

WORKDIR ${BASE_FOLDER}/${ROS_WORKSPACE_NAME}

COPY src/ src/

RUN find src/ -path "*/scripts/*" -type f -exec chmod +x {} \;

#rtabmap

# frontier exploration
RUN git clone https://github.com/Nyanziba/AutoFrontierSearch_ros2-humble.git

# nav2
RUN git clone https://github.com/ros-navigation/navigation2.git --branch $ROS_DISTRO ./src/navigation2

RUN apt-get update && \
    apt-get install -y ros-humble-gazebo-ros && \
    rosdep update && \
    rosdep install --from-paths src --ignore-src -r -y --skip-keys="gazebo_ros_pkgs" && \
    rm -rf /var/lib/apt/lists/*

RUN /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash && \
colcon build --parallel-workers $(nproc) --symlink-install \
    --event-handlers console_direct+ --base-paths src \
    --cmake-args \
        ' -DCMAKE_BUILD_TYPE=Release' \
        ' -DCMAKE_CXX_FLAGS=\"-Wl,--allow-shlib-undefined\"' \
        ' --no-warn-unused-cli'"

ENTRYPOINT ["/bin/bash", "-c", "source ${BASE_FOLDER}/${ROS_WORKSPACE_NAME}/install/setup.bash && exec \"$@\"", "bash"]