services:
  zed_container:
    image: erc-mars-rover_perception:latest
    container_name: zed_container
    runtime: nvidia
    privileged: true
    network_mode: host
    volumes:
      - /lib/modules/$(uname -r):/lib/modules/$(uname -r)
      - /run/nvargus:/run/nvargus
      - /tmp/argus_socket:/tmp/argus_socket
    devices:
      - /dev/video0:/dev/video0
    entrypoint: /bin/bash
    command: -c "source install/setup.bash && ros2 launch zed_wrapper zed_camera.launch.py camera_model:=zed2i"

  perception_container:
    image: erc-mars-rover_perception:latest
    container_name: perception_container
    runtime: nvidia
    privileged: true
    network_mode: host
    volumes:
      - /lib/modules/$(uname -r):/lib/modules/$(uname -r)
      - /run/nvargus:/run/nvargus
      - /tmp/argus_socket:/tmp/argus_socket
    devices:
      - /dev/video0:/dev/video0
    entrypoint: /bin/bash
    #command: -c "source install/setup.bash"
    tty: true
    stdin_open: true
    depends_on:
      - zed_container