services:
  zed_container:
    image: erc-mars-rover_perception:latest
    container_name: zed_container
    runtime: nvidia
    privileged: true
    network_mode: host
    volumes:
      - /lib/modules/$(uname -r):/lib/modules/$(uname -r)
      - /run/nvargus:/run/nvargus
      - /tmp/argus_socket:/tmp/argus_socket
      - zed_models:/usr/local/zed/resources
    devices:
      - /dev/video0:/dev/video0
    entrypoint: /bin/bash
    command: -c "source install/setup.bash && \
      ros2 launch zed_wrapper zed_camera.launch.py \
      camera_model:=zed2i \
      general.resolution:=2 \
      general.fps:=30 \
      depth.depth_mode:=0 \
      depth.min_depth:=0.30 \
      depth.max_depth:=4.0 \
      depth.confidence:=70 \
      depth.texture_confidence:=70 \
      pos_tracking.imu_fusion:=true"

  # perception_container:
  #   image: erc-mars-rover_perception:latest
  #   container_name: perception_container
  #   runtime: nvidia
  #   privileged: true
  #   network_mode: host
  #   volumes:
  #     - /lib/modules/$(uname -r):/lib/modules/$(uname -r)
  #     - /run/nvargus:/run/nvargus
  #     - /tmp/argus_socket:/tmp/argus_socket
  #   devices:
  #     - /dev/video0:/dev/video0
  #   entrypoint: /bin/bash
  #   command: -c "source install/setup.bash && ros2 run probe_detection detect_probe.py"
  #   depends_on:
  #     - zed_container

  Nav2_And_RTAB_container:
    image: erc-mars-rover_nav:latest
    container_name: nav2_and_rtab_container
    privileged: true
    network_mode: host
    volumes:
      - /lib/modules/$(uname -r):/lib/modules/$(uname -r)
      - /run/nvargus:/run/nvargus
      - /tmp/argus_socket:/tmp/argus_socket
    entrypoint: /bin/bash
    command: -c "source install/setup.bash && ros2 launch navigation nav2.launch.py"
    depends_on:
      - zed_container

volumes:
  zed_models:  # Define the Docker volume for ZED models