# Replace the base image with the new one
FROM ubuntu:jammy

ARG ROS_DISTRO=humble
ARG BASE_FOLDER=/root
ARG ROS_WORKSPACE_NAME=ERC-Mars-Rover
ARG DEBIAN_FRONTEND=noninteractive

WORKDIR ${BASE_FOLDER}/${ROS_WORKSPACE_NAME}

# Install additional system packages not necessarily in the base image
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3-pip \
    python3-dev \
    libopenblas-dev \
    libopenmpi-dev \
    openmpi-bin \
    openmpi-common \
    gfortran \
    nano \
    libomp-dev && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

# ###################################
# ###         Install ROS         ###
# ###################################

# Set up locale
RUN apt-get update && apt-get install -y locales && \
    locale-gen en_US en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

ENV LANG=en_US.UTF-8
ENV PYTHONIOENCODING=utf-8

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1

# Add ROS 2 repository
RUN apt-get update && apt-get install -y software-properties-common && \
    add-apt-repository universe

RUN apt-get update && apt-get install -y curl && \
    curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" > /etc/apt/sources.list.d/ros2.list

# Fix libbrotli1 version conflict and install ROS 2 Humble with dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends --allow-downgrades \
    libbrotli1=1.0.9-2build6 \
    libbrotli-dev \
    libfreetype6-dev \
    libfontconfig1-dev \
    ros-humble-desktop && \
    apt-get install ros-dev-tools -y && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

# Install additional utilities and tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    nano \
    iputils-ping \
    busybox \
    iproute2 \
    zstd \
    wget \
    less \
    cmake \
    curl \
    gnupg2 \
    build-essential \
    python3 \
    python3-pip \
    python3-dev \
    python3-setuptools \
    libusb-1.0-0-dev \
    libspnav-dev \
    libbluetooth-dev \
    libcwiid-dev \
    git \
    python3-rosdep2 \
    kmod && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean


# Cyclone DDS
RUN apt-get update && apt-get install -y ros-humble-rmw-cyclonedds-cpp && rm -rf /var/lib/apt/lists/*
ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

# ROS environment setup
RUN echo "source /opt/ros/humble/setup.bash" >> /root/.bashrc

# ROS dependencies
RUN apt-get update && \
    rosdep update && \
    apt-get install -y ros-humble-nmea-msgs ros-humble-geographic-msgs ros-humble-image-transport ros-humble-cob-srvs ros-humble-diagnostic-updater ros-humble-robot-localization ros-humble-point-cloud-transport && \
    rm -rf /var/lib/apt/lists/*

#  - - - - Install system wide packages - - - - 
# Install Nav2
RUN apt-get update && \
/bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash && \
apt-get install -y \
ros-${ROS_DISTRO}-navigation2 \
ros-${ROS_DISTRO}-nav2-bringup" && \
rm -rf /var/lib/apt/lists/*

# Install RTAB MAP
RUN apt-get update && \ 
apt install ros-$ROS_DISTRO-rtabmap-ros -y && \
rm -rf /var/lib/apt/lists/*

# - - - - - Instal Workspace specific packages - - - -

# Create workspace for ROS 2
COPY ../src/ src/

RUN cp ${BASE_FOLDER}/${ROS_WORKSPACE_NAME}/src/navigation/config/nav2_params.yaml /opt/ros/humble/share/nav2_bringup/params/nav2_params.yaml && \
    cp ${BASE_FOLDER}/${ROS_WORKSPACE_NAME}/src/navigation/config/navigation_launch.py /opt/ros/humble/share/nav2_bringup/launch/navigation_launch.py && \
    cp ${BASE_FOLDER}/${ROS_WORKSPACE_NAME}/src/navigation/config/navigate_to_pose_w_replanning_and_recovery.xml /opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml && \
    cp ${BASE_FOLDER}/${ROS_WORKSPACE_NAME}/src/navigation/config/navigate_through_poses_w_replanning_and_recovery.xml /opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_through_poses_w_replanning_and_recovery.xml
RUN find src/ -path "*/scripts/*" -type f -exec chmod +x {} \;

# Clone Frontier exploration
RUN git clone https://github.com/Nyanziba/AutoFrontierSearch_ros2-humble.git src/AutoFrontierSearch_ros2-humble && \
    cd src/AutoFrontierSearch_ros2-humble && \
    cp ${BASE_FOLDER}/${ROS_WORKSPACE_NAME}/src/navigation/config/algolism.py src/frontier_exploration/frontier_exploration/algolism.py

RUN /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash && \
    colcon build --parallel-workers $(nproc) --symlink-install \
        --event-handlers console_direct+ --base-paths src \
        --packages-skip livox_ros_driver2 probe_detection \
        --cmake-args \
            ' -DCMAKE_BUILD_TYPE=Release' \
            ' -DCMAKE_CXX_FLAGS=\"-Wl,--allow-shlib-undefined\"' \
            ' --no-warn-unused-cli'"

ENTRYPOINT ["/bin/bash", "-c", "source ${BASE_FOLDER}/${ROS_WORKSPACE_NAME}/install/setup.bash && exec \"$@\"", "bash"]